version: '3.9'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://postgres:postgres@unitybd/postgres?sslmode=disable
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - app-net
  #   depends_on:
  #     - unitybd

  unitybd:
    container_name: unitybd
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-net
    ports:
      - '5432:5432'
    env_file:
      - ./.env.pgsql

  # unitypgadmin:
  #   image: dpage/pgadmin4
  #   container_name: unitypgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@teste.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   command: sudo chown -R 5050:5050 ./pgadmin
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "5433:80"
  #   depends_on:
  #     - unitybd
  #   networks:
  #     - app-net

###############################################################################
# FIM DOS SERVICES
###############################################################################

networks:
  app-net:
    external:
      name: external-networks
